name: Metrics

on:
  schedule: [{cron: "0 * * * *"}]
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.10
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # What to display
          user: joseywoermann
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          plugin_isocalendar: yes
          plugin_lines: yes
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}      # Required
          plugin_wakatime_days: 36                                  # Display last week stats
          plugin_wakatime_limit: 0                                  # Show 4 entries per graph
          plugin_wakatime_url: https://wakatime.com                 # Wakatime url endpoint
          plugin_wakatime_user: .user.login                         # User
          plugin_projects_descriptions: yes
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
